name: shopizer CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Make Docker Image
        run: docker build . -t curvc/shopizer-shop-reactjs:latest

